//go:build !ignore_autogenerated

/*
Copyright 2024 River Point Technology.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	fleet_cattle_iov1alpha1 "github.com/rancher/fleet/pkg/apis/fleet.cattle.io/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetHandshake) DeepCopyInto(out *FleetHandshake) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetHandshake.
func (in *FleetHandshake) DeepCopy() *FleetHandshake {
	if in == nil {
		return nil
	}
	out := new(FleetHandshake)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetHandshake) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetHandshakeList) DeepCopyInto(out *FleetHandshakeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetHandshake, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetHandshakeList.
func (in *FleetHandshakeList) DeepCopy() *FleetHandshakeList {
	if in == nil {
		return nil
	}
	out := new(FleetHandshakeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetHandshakeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetHandshakeSpec) DeepCopyInto(out *FleetHandshakeSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]fleet_cattle_iov1alpha1.BundleTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetHandshakeSpec.
func (in *FleetHandshakeSpec) DeepCopy() *FleetHandshakeSpec {
	if in == nil {
		return nil
	}
	out := new(FleetHandshakeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetHandshakeStatus) DeepCopyInto(out *FleetHandshakeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetHandshakeStatus.
func (in *FleetHandshakeStatus) DeepCopy() *FleetHandshakeStatus {
	if in == nil {
		return nil
	}
	out := new(FleetHandshakeStatus)
	in.DeepCopyInto(out)
	return out
}
