---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes/finalizers
  verbs:
  - update
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes/status
  verbs:
  - get
  - patch
  - update
