apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleet-handshake.fullname" . }}-fleethandshake-editor-role
  labels:
  {{- include "fleet-handshake.labels" . | nindent 4 }}
rules:
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes/status
  verbs:
  - get
