apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleet-handshake.fullname" . }}-manager-role
  labels:
  {{- include "fleet-handshake.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes/finalizers
  verbs:
  - update
- apiGroups:
  - riverpointtechnology.com
  resources:
  - fleethandshakes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fleet-handshake.fullname" . }}-manager-rolebinding
  labels:
  {{- include "fleet-handshake.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "fleet-handshake.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "fleet-handshake.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
