apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fleet-handshake.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fleet-handshake.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
