apiVersion: v1
kind: Secret
metadata:
  name: fleethandshake-sample
  namespace: default
type: Opaque
stringData:
  fleet-handshake: apply
#  kubectl get bundle -o yaml fleethandshake-sample -o json | jq  -r '.spec.resources[0].content | fromjson | .data["fleet-handshake"]' | base64 -d
---
apiVersion: v1
kind: Secret
metadata:
  name: fleethandshake-test-only
  namespace: default
type: Opaque
stringData:
  fleet-handshake: test
