name: Publish Chart
on:
  push:
    branches:
      - main
    workflow_dispatch: {}
    paths:
      - 'charts/**'
      - .github/workflows/chart.yaml
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Configure Git
            run: |
              git config user.name "$GITHUB_ACTOR"
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
          - name: Install Helm
            uses: azure/setup-helm@v4
            env:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    
          - name: Run chart-releaser
            uses: helm/chart-releaser-action@v1.6.0
            with:
                charts_dir: charts
            env:
              CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
